// Code generated by MockGen. DO NOT EDIT.
// Source: repo_profession.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2023_2_Vkladyshi/pkg/models"
	gomock "github.com/golang/mock/gomock"
)

// MockIProfessionRepo is a mock of IProfessionRepo interface.
type MockIProfessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIProfessionRepoMockRecorder
}

// MockIProfessionRepoMockRecorder is the mock recorder for MockIProfessionRepo.
type MockIProfessionRepoMockRecorder struct {
	mock *MockIProfessionRepo
}

// NewMockIProfessionRepo creates a new mock instance.
func NewMockIProfessionRepo(ctrl *gomock.Controller) *MockIProfessionRepo {
	mock := &MockIProfessionRepo{ctrl: ctrl}
	mock.recorder = &MockIProfessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProfessionRepo) EXPECT() *MockIProfessionRepoMockRecorder {
	return m.recorder
}

// GetActorsProfessions mocks base method.
func (m *MockIProfessionRepo) GetActorsProfessions(actorId uint64) ([]models.ProfessionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActorsProfessions", actorId)
	ret0, _ := ret[0].([]models.ProfessionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActorsProfessions indicates an expected call of GetActorsProfessions.
func (mr *MockIProfessionRepoMockRecorder) GetActorsProfessions(actorId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActorsProfessions", reflect.TypeOf((*MockIProfessionRepo)(nil).GetActorsProfessions), actorId)
}
