// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindIdRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindIdRequest) Reset()         { *m = FindIdRequest{} }
func (m *FindIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindIdRequest) ProtoMessage()    {}
func (*FindIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *FindIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindIdRequest.Unmarshal(m, b)
}
func (m *FindIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindIdRequest.Marshal(b, m, deterministic)
}
func (m *FindIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindIdRequest.Merge(m, src)
}
func (m *FindIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindIdRequest.Size(m)
}
func (m *FindIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindIdRequest proto.InternalMessageInfo

func (m *FindIdRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type FindIdResponse struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindIdResponse) Reset()         { *m = FindIdResponse{} }
func (m *FindIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindIdResponse) ProtoMessage()    {}
func (*FindIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *FindIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindIdResponse.Unmarshal(m, b)
}
func (m *FindIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindIdResponse.Marshal(b, m, deterministic)
}
func (m *FindIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindIdResponse.Merge(m, src)
}
func (m *FindIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindIdResponse.Size(m)
}
func (m *FindIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindIdResponse proto.InternalMessageInfo

func (m *FindIdResponse) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type NamesAndPathsListRequest struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamesAndPathsListRequest) Reset()         { *m = NamesAndPathsListRequest{} }
func (m *NamesAndPathsListRequest) String() string { return proto.CompactTextString(m) }
func (*NamesAndPathsListRequest) ProtoMessage()    {}
func (*NamesAndPathsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *NamesAndPathsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamesAndPathsListRequest.Unmarshal(m, b)
}
func (m *NamesAndPathsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamesAndPathsListRequest.Marshal(b, m, deterministic)
}
func (m *NamesAndPathsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamesAndPathsListRequest.Merge(m, src)
}
func (m *NamesAndPathsListRequest) XXX_Size() int {
	return xxx_messageInfo_NamesAndPathsListRequest.Size(m)
}
func (m *NamesAndPathsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NamesAndPathsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NamesAndPathsListRequest proto.InternalMessageInfo

func (m *NamesAndPathsListRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type NamesAndPathsResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Paths                []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamesAndPathsResponse) Reset()         { *m = NamesAndPathsResponse{} }
func (m *NamesAndPathsResponse) String() string { return proto.CompactTextString(m) }
func (*NamesAndPathsResponse) ProtoMessage()    {}
func (*NamesAndPathsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *NamesAndPathsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamesAndPathsResponse.Unmarshal(m, b)
}
func (m *NamesAndPathsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamesAndPathsResponse.Marshal(b, m, deterministic)
}
func (m *NamesAndPathsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamesAndPathsResponse.Merge(m, src)
}
func (m *NamesAndPathsResponse) XXX_Size() int {
	return xxx_messageInfo_NamesAndPathsResponse.Size(m)
}
func (m *NamesAndPathsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamesAndPathsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamesAndPathsResponse proto.InternalMessageInfo

func (m *NamesAndPathsResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *NamesAndPathsResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type AuthorizationCheckRequest struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationCheckRequest) Reset()         { *m = AuthorizationCheckRequest{} }
func (m *AuthorizationCheckRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCheckRequest) ProtoMessage()    {}
func (*AuthorizationCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AuthorizationCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationCheckRequest.Unmarshal(m, b)
}
func (m *AuthorizationCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationCheckRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizationCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCheckRequest.Merge(m, src)
}
func (m *AuthorizationCheckRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizationCheckRequest.Size(m)
}
func (m *AuthorizationCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCheckRequest proto.InternalMessageInfo

func (m *AuthorizationCheckRequest) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type AuthorizationCheckResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizationCheckResponse) Reset()         { *m = AuthorizationCheckResponse{} }
func (m *AuthorizationCheckResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationCheckResponse) ProtoMessage()    {}
func (*AuthorizationCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *AuthorizationCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizationCheckResponse.Unmarshal(m, b)
}
func (m *AuthorizationCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizationCheckResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizationCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizationCheckResponse.Merge(m, src)
}
func (m *AuthorizationCheckResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizationCheckResponse.Size(m)
}
func (m *AuthorizationCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizationCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizationCheckResponse proto.InternalMessageInfo

func (m *AuthorizationCheckResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type RoleRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleRequest) Reset()         { *m = RoleRequest{} }
func (m *RoleRequest) String() string { return proto.CompactTextString(m) }
func (*RoleRequest) ProtoMessage()    {}
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *RoleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleRequest.Unmarshal(m, b)
}
func (m *RoleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleRequest.Marshal(b, m, deterministic)
}
func (m *RoleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleRequest.Merge(m, src)
}
func (m *RoleRequest) XXX_Size() int {
	return xxx_messageInfo_RoleRequest.Size(m)
}
func (m *RoleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoleRequest proto.InternalMessageInfo

func (m *RoleRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type RoleResponse struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleResponse) Reset()         { *m = RoleResponse{} }
func (m *RoleResponse) String() string { return proto.CompactTextString(m) }
func (*RoleResponse) ProtoMessage()    {}
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *RoleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleResponse.Unmarshal(m, b)
}
func (m *RoleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleResponse.Marshal(b, m, deterministic)
}
func (m *RoleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleResponse.Merge(m, src)
}
func (m *RoleResponse) XXX_Size() int {
	return xxx_messageInfo_RoleResponse.Size(m)
}
func (m *RoleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoleResponse proto.InternalMessageInfo

func (m *RoleResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*FindIdRequest)(nil), "auth.FindIdRequest")
	proto.RegisterType((*FindIdResponse)(nil), "auth.FindIdResponse")
	proto.RegisterType((*NamesAndPathsListRequest)(nil), "auth.NamesAndPathsListRequest")
	proto.RegisterType((*NamesAndPathsResponse)(nil), "auth.NamesAndPathsResponse")
	proto.RegisterType((*AuthorizationCheckRequest)(nil), "auth.AuthorizationCheckRequest")
	proto.RegisterType((*AuthorizationCheckResponse)(nil), "auth.AuthorizationCheckResponse")
	proto.RegisterType((*RoleRequest)(nil), "auth.RoleRequest")
	proto.RegisterType((*RoleResponse)(nil), "auth.RoleResponse")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x8e, 0xd3, 0x30,
	0x14, 0xc6, 0xe9, 0x74, 0x32, 0x30, 0x0f, 0x66, 0x04, 0xa6, 0x8c, 0x42, 0x90, 0xa0, 0x18, 0x09,
	0xcd, 0x82, 0x69, 0x50, 0xda, 0x0b, 0x94, 0x4a, 0x54, 0x95, 0x10, 0x54, 0x46, 0x62, 0x81, 0x84,
	0x2a, 0x83, 0x0d, 0xb1, 0x1a, 0xe2, 0x12, 0x3b, 0x48, 0xb0, 0xe2, 0x06, 0x6c, 0xb9, 0x02, 0x3b,
	0x58, 0xf0, 0x67, 0x03, 0x67, 0x70, 0x6f, 0x34, 0xb2, 0x9d, 0x56, 0x89, 0xd4, 0xac, 0xf2, 0xbe,
	0xe7, 0xdf, 0xfb, 0x6c, 0x7f, 0x0e, 0x00, 0x2d, 0x75, 0x3a, 0x58, 0x15, 0x52, 0x4b, 0xb4, 0x6f,
	0x6b, 0x7c, 0x17, 0x8e, 0x1e, 0x8b, 0x9c, 0xcd, 0x18, 0xe1, 0x1f, 0x4a, 0xae, 0x34, 0xba, 0x0a,
	0x5d, 0x25, 0x58, 0xd8, 0xe9, 0x77, 0x4e, 0x0f, 0x89, 0x2d, 0xf1, 0x7d, 0x38, 0xde, 0x20, 0x6a,
	0x25, 0x73, 0xc5, 0x51, 0x0f, 0x82, 0x8f, 0x34, 0x2b, 0xb9, 0xa3, 0xba, 0xc4, 0x0b, 0xfc, 0x00,
	0xc2, 0xa7, 0xf4, 0x3d, 0x57, 0xe3, 0x9c, 0xcd, 0xa9, 0x4e, 0xd5, 0x13, 0xa1, 0x74, 0xcd, 0x55,
	0x30, 0x15, 0x76, 0xfa, 0xdd, 0xd3, 0x80, 0xd8, 0x12, 0x4f, 0xe0, 0x46, 0x83, 0xae, 0x9b, 0xe7,
	0x76, 0xc1, 0xc1, 0x87, 0xc4, 0x0b, 0xdb, 0x5d, 0x59, 0x2c, 0xdc, 0xf3, 0x5d, 0x27, 0xf0, 0x19,
	0xdc, 0x1c, 0x97, 0x3a, 0x95, 0x85, 0xf8, 0x4c, 0xb5, 0x90, 0xf9, 0x24, 0xe5, 0x6f, 0x96, 0xed,
	0x37, 0x19, 0x41, 0xb4, 0x0b, 0xaf, 0x36, 0x3e, 0x81, 0x03, 0xa5, 0xa9, 0x2e, 0x95, 0x1b, 0xb9,
	0x44, 0x2a, 0x85, 0xef, 0xc1, 0x65, 0x22, 0x33, 0xbe, 0xb1, 0xed, 0x41, 0x90, 0xc9, 0x77, 0x22,
	0xaf, 0x8c, 0xbd, 0xc0, 0x18, 0xae, 0x78, 0xa8, 0x32, 0x43, 0xb0, 0x5f, 0xc8, 0x8c, 0x57, 0x90,
	0xab, 0x93, 0xef, 0x7b, 0x70, 0xd4, 0xd8, 0x1f, 0x8d, 0x20, 0x98, 0x72, 0x3d, 0x63, 0xe8, 0xfa,
	0xc0, 0xbd, 0x4c, 0xe3, 0x29, 0xa2, 0x5e, 0xb3, 0xe9, 0x9d, 0xf1, 0x05, 0xf4, 0x0c, 0x8e, 0xdd,
	0xd4, 0x36, 0x3b, 0x74, 0xdb, 0x93, 0x6d, 0xf1, 0x47, 0xb7, 0x76, 0xac, 0xd7, 0x0c, 0x5f, 0xc1,
	0xc9, 0x94, 0xeb, 0xc6, 0xd1, 0x9e, 0xbb, 0xbb, 0xa3, 0x3b, 0x7e, 0xb0, 0x35, 0xe4, 0xa8, 0xdf,
	0x0e, 0x6c, 0xed, 0x13, 0xb8, 0x38, 0xe5, 0xda, 0xc6, 0x83, 0xae, 0x79, 0xbc, 0x96, 0x67, 0x84,
	0xea, 0xad, 0xcd, 0xcc, 0x23, 0xf2, 0x72, 0x1e, 0x9b, 0x6f, 0xe6, 0x8f, 0xf9, 0x6f, 0x7e, 0xae,
	0xbf, 0x98, 0x1f, 0xe6, 0xb7, 0xf9, 0x65, 0xfe, 0x99, 0xbf, 0xeb, 0xaf, 0x71, 0xf2, 0x30, 0x19,
	0x2e, 0x92, 0xc5, 0x8b, 0x65, 0x46, 0xd9, 0x27, 0x95, 0x8a, 0x33, 0xca, 0x98, 0xb0, 0xfb, 0xd2,
	0x6c, 0xf1, 0x96, 0x53, 0x5d, 0x16, 0x5c, 0xc5, 0xb4, 0x7e, 0xa0, 0xd8, 0xfd, 0xf1, 0xaf, 0x0f,
	0xdc, 0x67, 0x78, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xad, 0x7f, 0x03, 0x4a, 0x06, 0x03, 0x00, 0x00,
}
